config/routes.rb
ConsolidatorApp::Application.routes.draw do
  get "consolidator/companies"
  get "home/index"

  root 'home#index'
  get 'companies/' => 'consolidator#companies'
  post 'companies/' => 'consolidator#create'
  get 'companies/new' => 'consolidator#new'
  get 'companies/:id' => 'consolidator#show', :as => :company
  patch 'companies/:id' => 'consolidator#show'

  

end

app/models/company.rb
class Company < ActiveRecord::Base
	validates	:name, presence: true
	has_many :subsidiaries, class_name: "Company", foreign_key: "parent_id"
	belongs_to :parent, class_name: "Company"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/consolidator_controller.rb
class ConsolidatorController < ApplicationController
	def companies
		@companies = Company.all
	end

	def show
  		if request.get?
  			@company = Company.find(params[:id])
  			@companies = Company.all
  			@companies = (Company.find(:all, :conditions => ["id != ?", @company.id]))
  		
  		else
  			@company = Company.find(params[:id])	
  			selected_subsidiaries = params[:company][:subsidiary_ids]
  			if selected_subsidiaries
	  			if selected_subsidiaries.count{ |item| !item.blank? } == 0
	  				Company.where(parent_id: @company.id).update_all(parent_id: nil)
	  			else
	  				Company.where(parent_id: @company.id).update_all(parent_id: nil)
	  				Company.where(id: selected_subsidiaries.reject! { |c| c.empty? }).update_all(parent_id: @company.id)	
	  			end
	  		end

			if @company.update(company_params)
				redirect_to @company
			else
				render 'show'
			end
  		end
  	end

	def new
  		@company = Company.new
	end

	def create
		@company = Company.new(company_params)
		if @company.save
			redirect_to @company
		else
			render 'companies'
		end
  	end

  private
  	def company_params
  		params.require(:company).permit(:name, :black_males, :black_females, :white_males, :white_females)
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consolidator_helper.rb
module ConsolidatorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/consolidator/companies.html.erb
<% content_for :titlebar do -%>
  <h1>All companies</h1>
<% end -%>


<% if @companies.length > 0 %>
	<ul>
	<% @companies.each do |company| %>
		<li><%= link_to  "#{company.name} #{company.subsidiaries.length > 0 ? "(#{company.subsidiaries.length} subsidiaries)" :"" }", company_path(@company, :id => company.id) %></td>
	<% end %>
	</ul>
<% else %>	
	No companies found. <%= link_to "Add a company","/companies/new/" %>
<% end %>

app/views/consolidator/new.html.erb
<% content_for :titlebar do -%>
  <h1>New company</h1>
<% end -%>


<%= form_for :company, url: companies_path do |c| %>
  <p>
    <%= c.label :name %><br>
    <%= c.text_field :name %>
  </p> 
  <p>
    <%= c.submit %>
  </p>
<% end %>

app/views/consolidator/show.html.erb
<% content_for :titlebar do -%>
  <h1><%= link_to "All companies", companies_path %> > <%= @company.name %></h1>
<% end -%>

<% if @company.subsidiaries.length == 0 %>
  <h3><%= @company.name %> demographics</h3>
  <br>
  <%= form_for :company, url: company_path(@company.id), method: :patch do |f| %>
    <table>
    	<tr>
    		<td></td>
    		<td>Black</td>
    		<td>White</td>
    	</tr>
    	<tr>
    		<td>Males</td>
    		<td><%= f.text_field :black_males %></td>
    		<td><%= f.text_field :white_males %></td>
    	</tr>
    	<tr>
    		<td>Females</td>
    		<td><%= f.text_field :black_females %></td>
    		<td><%= f.text_field :white_females %></td>
    	</tr>
    </table>
    <p>
      <%= f.submit "Save demographics" %>
    </p>

  <% end %>
<% else %>
  <h3><%= @company.name %> consolidated demographics</h3>

  <table>
    <tr>
      <td></td>
      <td>Black</td>
      <td>White</td>
    </tr>
    <tr>
      <td>Males</td>
      <td><%= @company.subsidiaries.sum("black_males") %></td>
      <td><%= @company.subsidiaries.sum("white_males") %></td>
    </tr>
    <tr>
      <td>Females</td>
      <td><%= @company.subsidiaries.sum("black_females") %></td>
      <td><%= @company.subsidiaries.sum("white_females") %></td>
    </tr>
  </table>
<% end %>
<h4>Immediate subsidiaries</h4>
   <%= form_for :company, url: company_path(@company.id), method: :patch do |c| %>
      <ul>
        <% @companies.each do |company| %>
          <li>
            <%= hidden_field_tag "company[subsidiary_ids][]" %>
            <%= link_to  "#{company.name} #{company.subsidiaries.length > 0 ? "(#{company.subsidiaries.length} subsidiaries)" :"" }", company_path(@company, :id => company.id) %> 
            <%= check_box_tag "company[subsidiary_ids][]", company.id, @company.subsidiaries.include?(company), :id => "company_subsidiary_ids_#{company.id}" %>
          </li>
        <% end %>
      </ul>
      <p><%= c.submit "Add to consolidation" %></p>
    <% end %>

app/views/home/index.html.erb
<h1>Consolidator</h1>
<p>Enter</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConsolidatorApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
	<div id="titlebar">
		<%= yield :titlebar %>
	</div>
	<div id="content">
		<%= yield %>
	</div>

</div>
</body>
</html>